### ISSUE TITLE
Parse errors not fully handled, as many different exceptions can be raised

### ISSUE THREAD

**Issue by kormat** [netsec-ethz/scion#525]
Here's an example:

```
 Exception in CS.worker thread:
 Traceback (most recent call last):
   File "/home/adrian/github/scion/lib/thread.py", line 48, in thread_safety_net
     return func(*args, **kwargs)
   File "infrastructure/cert_server.py", line 107, in worker
     self.trc_cache.process()
   File "/home/adrian/github/scion/lib/zookeeper.py", line 605, in process
     count = self._handle_entries(current - previous)
   File "/home/adrian/github/scion/lib/zookeeper.py", line 670, in _handle_entries
     self._handler(data)
   File "infrastructure/cert_server.py", line 123, in _cached_entries_handler
     pkt = SCIONL4Packet(raw=entry)
   File "/home/adrian/github/scion/lib/packet/scion.py", line 476, in __init__
     self._parse(raw)
   File "/home/adrian/github/scion/lib/packet/scion.py", line 291, in _parse
     self._inner_parse(data)
   File "/home/adrian/github/scion/lib/packet/scion.py", line 479, in _inner_parse
     super()._inner_parse(data)
   File "/home/adrian/github/scion/lib/packet/scion.py", line 416, in _inner_parse
     super()._inner_parse(data)
   File "/home/adrian/github/scion/lib/packet/scion.py", line 296, in _inner_parse
     self._parse_cmn_hdr(data)
   File "/home/adrian/github/scion/lib/packet/scion.py", line 302, in _parse_cmn_hdr
     self.cmn_hdr = SCIONCommonHdr(data.pop(SCIONCommonHdr.LEN))
   File "/home/adrian/github/scion/lib/packet/scion.py", line 87, in __init__
     self._parse(raw)
   File "/home/adrian/github/scion/lib/packet/scion.py", line 101, in _parse
     self.dst_addr_type)
   File "/home/adrian/github/scion/lib/packet/scion.py", line 234, in calc_len
     src_class = haddr_get_type(src_type)
   File "/home/adrian/github/scion/lib/packet/host_addr.py", line 208, in haddr_get_type
     type_) from None
 lib.packet.host_addr.HostAddrInvalidType: Unknown host addr type '44'
```

**Comment by kormat** [comment]
#528 is done, and although there are sure to be some remaining errors that aren't handled, having a vague catch-all issue open doesn't help.
