### ISSUE TITLE
Unable to find first hop -> crash

### ISSUE THREAD

**Issue by kormat** [netsec-ethz/scion#916]
This only happens sometimes, and the reasons for the first hop lookup failing aren't clear, but whenever it does fail, the error isn't handled correctly, and leads to an assertion failure soon after. 

https://circleci.com/gh/netsec-ethz/scion/3832 is an example.
```
2016-10-17 12:55:57.852771+00:00 [ERROR] (MainThread) Unable to find first hop:
<SCION-Path>
  <A-Segment>
    InfoOpaqueField(8B): flags: UP, TS: 2016-10-17 12:55:52+00:00, ISD: 2, hops: 3
    HopOpaqueField(8B): flags: None, exp_time: 63, ingress: 0, egress: 35, mac: 61c638
    HopOpaqueField(8B): flags: None, exp_time: 63, ingress: 96, egress: 54, mac: 7f9681
    HopOpaqueField(8B): flags: None, exp_time: 63, ingress: 88, egress: 0, mac: 4b29fc
  </A-Segment>
</SCION-Path>
2016-10-17 12:55:58.249931+00:00 [DEBUG] (Elem.packet_recv) _get_msg_meta() called
2016-10-17 12:55:58.251552+00:00 [CRITICAL] (MainThread) Exception in main process:
2016-10-17 12:55:58.252800+00:00 [CRITICAL] (MainThread) Traceback (most recent call last):
2016-10-17 12:55:58.253085+00:00 [CRITICAL] (MainThread)   File "/home/scion/go/src/github.com/netsec-ethz/scion/lib/main.py", line 37, in main_wrapper
2016-10-17 12:55:58.253398+00:00 [CRITICAL] (MainThread)     main(*args, **kwargs)
2016-10-17 12:55:58.253663+00:00 [CRITICAL] (MainThread)   File "/home/scion/go/src/github.com/netsec-ethz/scion/lib/main.py", line 81, in main_default
2016-10-17 12:55:58.254229+00:00 [CRITICAL] (MainThread)     inst.run()
2016-10-17 12:55:58.254786+00:00 [CRITICAL] (MainThread)   File "/home/scion/go/src/github.com/netsec-ethz/scion/infrastructure/path_server/base.py", line 380, in run
2016-10-17 12:55:58.255248+00:00 [CRITICAL] (MainThread)     super().run()
2016-10-17 12:55:58.255512+00:00 [CRITICAL] (MainThread)   File "/home/scion/go/src/github.com/netsec-ethz/scion/infrastructure/scion_elem.py", line 513, in run
2016-10-17 12:55:58.255774+00:00 [CRITICAL] (MainThread)     self._packet_process()
2016-10-17 12:55:58.256034+00:00 [CRITICAL] (MainThread)   File "/home/scion/go/src/github.com/netsec-ethz/scion/infrastructure/scion_elem.py", line 619, in _packet_process
2016-10-17 12:55:58.256307+00:00 [CRITICAL] (MainThread)     self.handle_msg_meta(*self._in_buf.get(timeout=1.0))
2016-10-17 12:55:58.256594+00:00 [CRITICAL] (MainThread)   File "/home/scion/go/src/github.com/netsec-ethz/scion/infrastructure/scion_elem.py", line 234, in handle_msg_meta
2016-10-17 12:55:58.256906+00:00 [CRITICAL] (MainThread)     handler(msg, meta)
2016-10-17 12:55:58.257297+00:00 [CRITICAL] (MainThread)   File "/home/scion/go/src/github.com/netsec-ethz/scion/infrastructure/path_server/base.py", line 274, in handle_path_segment_record
2016-10-17 12:55:58.257806+00:00 [CRITICAL] (MainThread)     added.update(self._dispatch_segment_record(type_, pcb, **params))
2016-10-17 12:55:58.258290+00:00 [CRITICAL] (MainThread)   File "/home/scion/go/src/github.com/netsec-ethz/scion/infrastructure/path_server/base.py", line 285, in _dispatch_segment_record
2016-10-17 12:55:58.258767+00:00 [CRITICAL] (MainThread)     return handle_map[type_](seg, **kwargs)
2016-10-17 12:55:58.259278+00:00 [CRITICAL] (MainThread)   File "/home/scion/go/src/github.com/netsec-ethz/scion/infrastructure/path_server/core.py", line 137, in _handle_core_segment_record
2016-10-17 12:55:58.259715+00:00 [CRITICAL] (MainThread)     self._handle_waiting_targets(pcb, reverse=reverse)
2016-10-17 12:55:58.260151+00:00 [CRITICAL] (MainThread)   File "/home/scion/go/src/github.com/netsec-ethz/scion/infrastructure/path_server/base.py", line 325, in _handle_waiting_targets
2016-10-17 12:55:58.260721+00:00 [CRITICAL] (MainThread)     self._send_waiting_queries(dst_ia[0], pcb)
2016-10-17 12:55:58.261266+00:00 [CRITICAL] (MainThread)   File "/home/scion/go/src/github.com/netsec-ethz/scion/infrastructure/path_server/base.py", line 337, in _send_waiting_queries
2016-10-17 12:55:58.261791+00:00 [CRITICAL] (MainThread)     self.send_meta(seg_req, meta)
2016-10-17 12:55:58.262312+00:00 [CRITICAL] (MainThread)   File "/home/scion/go/src/github.com/netsec-ethz/scion/infrastructure/scion_elem.py", line 457, in send_meta
2016-10-17 12:55:58.262829+00:00 [CRITICAL] (MainThread)     return self.send(pkt, *next_hop_port)
2016-10-17 12:55:58.263347+00:00 [CRITICAL] (MainThread)   File "/home/scion/go/src/github.com/netsec-ethz/scion/infrastructure/scion_elem.py", line 431, in send
2016-10-17 12:55:58.263875+00:00 [CRITICAL] (MainThread)     assert isinstance(dst_port, int), dst_port
2016-10-17 12:55:58.264439+00:00 [CRITICAL] (MainThread) AssertionError
2016-10-17 12:55:58.265000+00:00 [CRITICAL] (MainThread) 
2016-10-17 12:55:58.265338+00:00 [CRITICAL] (MainThread) Exiting

```

**Comment by kormat** [comment]
I believe this was introduced with the TCP changes, hence assigning to @pszalach

**Comment by kormat** [comment]
Another example: https://circleci.com/gh/netsec-ethz/scion/3823

**Comment by kormat** [comment]
Ok, after looking at this more closely, here's what's happening:

- Sometimes the first core PCB a PS receives for a remote ISD is a SIBRA one, as the normal PCB didn't make it. In the first case above, this is because bs2-22 didn't start until after bs2-21 tried to propagate the PCB from 1-11.
- If there are already waiting queries for the remote ISD, the ps then tries to send queries using the path contained in the PCB. However, as it's a SIBRA PCB, the field ordering is different, and the resulting path incorrectly has the `UP` flag set.
- `get_first_hop()` determines the IFID to be 0, and returns `(None, None`).
- `send_meta()` fails to detect this correctly, and passes this into `send`, which then fails an assertion, as the port isn't an int.

**Comment by kormat** [comment]
It's only the logic for waiting targets/queries that is broken. If the SIBRA PCB was received before the path request, nothing breaks. This means that normally the request has to happen soon after startup, as SIBRA core/steady paths are setup 30s after start. It also only breaks if the SIBRA PCB in question was generated by a remote AS, one from the local SIBRA service is fine, as its fields are differently ordered.

I can reproduce this 100% with the following hacks to the code:
- Start with no cached PCBs
- Have ps2-22-1 drop all non-SIBRA pcbs from ISD 1.
- Have sb's never remotely register paths with 2-22.
- Run `end2end 2-22 1-19` (for example) immediately after startup.

**Comment by pszalach** [comment]
@kormat btw what's the reason for this 30s delay?

**Comment by kormat** [comment]
@pszalach: so that the sibra service has a chance to see what segments are available before making reservations.
